name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name
    - name: save
      run: docker save my-image-name | zstd > my-image-name.tar.zst
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: my-image-name.tar.zst
        asset_name: my-image-name.tar.zst
        tag: ${{ github.ref }}
        overwrite: true
